### PR TITLE
added booklists

### PR DESCRIPTION
**Pull request by evanhearne**
So, basically I was trying to resolve conflicts on #70  , but I messed up and actually deleted the entire history of the branch, which isn't cool and I apologise. But, I was luckily able to recover all the files that were edited and so I am putting them here. 

Again, sorry about that.

### CODE REVIEW

**Comment by evanhearne** [comment]
@denispop9 can you look at this branch and take a screenshot of all pages and post them on the Trello card? Also could you ask the stakeholders' opinion?

**Comment by denispop9** [comment]
@evanhearne yes no problem

**Comment by laurafitzgerald** [comment]
@denispop9 thanks for the info. I would say the easiest approach here is to update the navigation for the booklist files and complete the curriculum in a separate pr. This one has been open for a while so it would be good to get it closed out.

**Comment by evanhearne** [comment]
@laurafitzgerald thanks for giving us advice on what to do from here, @denispop9 shall I do this or do you feel comfortable enough proceeding with the next steps on this PR? Meanwhile, I will add a card to our Trello board concerning the curriculum.

**Comment by evanhearne** [comment]
@laurafitzgerald I spoke with @denispop9 and he said to me that he would like me to work on the navbar since it is my expertise. I will ping you again for review when it's done.

**Pull request merged**
