### PR TITLE
Evanhearne1 adding assessment content

### PR DESCRIPTION
**Pull request by evanhearne**
# Description

Deleted assesment.html in /pages/about/policies/ due to it being misspelt correctly. Added a new file names assessment.html in /pages/about/policies/ to replace the misspelt assesment.html. Added content to assessment.html in /pages/about/policies/.  Adjusted policies.html function in /pages/about/policies.html so as it will recognize assessment.html found in /pages/about/policies/ when the 'Read More' button is clicked. I still need to make changes to the blurb section of the Policies part of the website.

## What

Deleted assesment.html in /pages/about/policies/ due to it being misspelt correctly. Added a new file names assessment.html in /pages/about/policies/ to replace the misspelt assesment.html. Added content to assessment.html in /pages/about/policies/.  Adjusted policies.html function in /pages/about/policies.html so as it will recognize assessment.html found in /pages/about/policies/ when the 'Read More' button is clicked.

## Why

Because it will add functionality to the 'Assessment' part of the 'Policies' section of the website.

## How

All changes were made via Sublime Text 3 using [this](https://www.wordhtml.com).

## Verification Steps

What steps were taken to verify the change is working correctly

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [ ] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by evanhearne** [comment]
@denispop9 @laurafitzgerald can you please have a look at this and give me some feedback on it? :)

**Comment by evanhearne** [comment]
@laurafitzgerald @denispop9 added quotation marks to Assessment Policy blurb and also added in the title with bold italics into the same blurb in policies.html in /pages/about/ :)

**Comment by laurafitzgerald** [comment]
@evanhearne I just noticed that the description underneath `Verification Steps` is not accurate. It says what steps were taken but it should say `What steps should be taken to verify....` I am going to create a card on the trello board to get his updated which either you or @denispop9 can work on. I've also updated the team trello board so that we have `To Do, Doing, Done` column to track the work you guys will do in the next couple of days.

**Comment by laurafitzgerald** [comment]
Aside form the above I'm 👀 this pr now.

**Comment by evanhearne** [comment]
@laurafitzgerald Unfortunately, I don't have write access, but you do. So if you could merge this for me, that'd be very much appreciated. :)

**Pull request merged**
