### PR TITLE
Made doc folder and put tutorial in it 

### PR DESCRIPTION
**Pull request by dominikkawka**

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@dominikkawka this looks good so far. It would be better to get to the other pr you have merged first and then rebase it. I see you are deleting the licence.md file but you are already taking care of that in the other pr. Once it's merged you can rebase this branch against master to resolve that.

**Comment by dominikkawka** [comment]
sorry for responding so late, I got distracted by something, anyway, the only thing left to do is to rebase this pr right? Is there nothing left that I should change with the tutorial?

**Comment by ciaranRoche** [comment]
Yeah if you could rebase and we should be ok to merge then. If anything else comes up or if we need to add to the tutorial we can make another PR on a later date.
Any problems with the rebase ping me on slack.

**Comment by dominikkawka** [comment]
I'm currently at work and away from my pc. I'll do the rebase when I'm back home

**Comment by dominikkawka** [comment]
I tried to rebase, but said that everything is up to date 
okay

**Comment by dominikkawka** [comment]
is there nothing left to do for this branch except to wait for it to be merged?

**Comment by ciaranRoche** [comment]
@dominikkawka Nothing left to do, once we merge the new folder structure, you can rebase off that and when @laurafitzgerald gives the thumbs up on this you can then merge it

**Comment by dominikkawka** [comment]
what is the change that you want me to do @laurafitzgerald I don't understand

**Comment by laurafitzgerald** [comment]
@dominikkawka I've merged the pr mentioned by @ciaranRoche above. This branch will need to be rebased against master before being merged. Give me a shout in slack if you want any help with it or if it's not clear what has to be done.

**Comment by dominikkawka** [comment]
Is it rebased now? Windows is being a pain. I'm going to switch to fedora 27 after this pr has been accepted

**Comment by laurafitzgerald** [comment]
@dominikkawka looks good, feel free to merge

**Pull request merged**
