### PR TITLE
added 1-6th year booklists

### PR DESCRIPTION
**Pull request by denispop9**
# Description

added 1-6th year booklists

## What

People can now see the booklists.

## Why

So people will be informed of the booklists for the following year.

## How

By adding the booklist to the site

## Verification Steps

What steps should be taken to verify that the change is working correctly

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by denispop9** [comment]
@laurafitzgerald @evanhearne Can you have a look at this for me?

**Comment by laurafitzgerald** [comment]
@denispop9 the change looks. I think there's some more to go in there so will wait before leaving a full review. Would you double check that they should go under the curriculum navigation item. Perhaps it would be better to call that booklist. wdyt? Or maybe we could run it by the stakeholders to see what they're thoughts were about where the booklists should go.

**Comment by laurafitzgerald** [comment]
@denispop9 Did you get any opportunity to discuss the question I left above with the stakeholders? I also see that you've added further changes here so feel free to ping me when you are ready for a review.

**Comment by laurafitzgerald** [comment]
@denispop9 ok that's fine. Could you ask them to leave a note in the trello to that effect. Do you want me to review this now?

**Comment by evanhearne** [comment]
Hello @laurafitzgerald that was me @evanhearne speaking to you. I will ask
Denis personally to respond to you. :)

**Comment by laurafitzgerald** [comment]
@evanhearne thanks. I assumed it was Denis as it was him i pinged. Thanks for answering the question. I will wait for @denispop9 to get back before doing any review.

**Comment by laurafitzgerald** [comment]
By the way we don't have to change the name from curriculum to booklist. We could just add an additional navigation item titled booklists.

**Comment by denispop9** [comment]
@laurafitzgerald could you review this for me please? I think everything is ready to go. Is there a point in adding a booklist navigation tab?

**Comment by laurafitzgerald** [comment]
@denispop9 taking a look at this now. Will leave a review shortly

**Comment by denispop9** [comment]
I'll add in the lcvp content to the page and then I will merge :)

**Comment by edkennedy50** [comment]
That’s perfect Denis.Thanks.

**Comment by evanhearne** [comment]
@denispop9 just a gentle reminder that you have outstanding work on the PR to complete before merging. Maybe you can perhaps work on this on Monday?

**Comment by evanhearne** [comment]
@denispop9 will review this now.

**Comment by evanhearne** [comment]
@laurafitzgerald, I have requested the stakeholders to look at the
screenshots on the trello card related to this PR which contain samples of
the booklists. All we can do is wait for their opinion.

**Comment by evanhearne** [comment]
@laurafitzgerald I spoke with @Gally88 and he said to leave it, just waiting on @edkennedy50's response.

**Comment by denispop9** [comment]
@laurafitzgerald Mr. Galvin said to leave it as it is.

**Comment by denispop9** [comment]
@laurafitzgerald I have a conflict I've been trying to fix it but I'm not sure how to could you help me with it please.

**Comment by evanhearne** [comment]
@denispop9 I can help you with this if you like. Meanwhile have a look at the `docs` folder for the git commands where it shows how to rebase files.

**Pull request closed without merging**
