### PR TITLE
history

### PR DESCRIPTION
**Pull request by SinenWew**
# Description

History document was added onto the site

## What

History document is now present in the history tab

## Why

The history of Mount Sion needed to be displayed

## How

Made separate history branch, edited history text through wordhtml. History text was put into the 'history.html' file.

## Verification Steps

http-server 
ensure history text is in the history.html tab

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [ ] I have requested a code review from (at least) two team members
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This change has been verified by another team member

### CODE REVIEW

**Comment by SinenWew** [comment]
@evanhearne UWU

**Comment by evanhearne** [comment]
@SinenWew could you attach this to the related Trello Card?

**Comment by evanhearne** [comment]
@SinenWew thanks for attaching that. I will review it, but there seems to be a conflict. I will help you with this after I check to see if changes are working.

**Comment by evanhearne** [comment]
@SinenWew changes work fine, we will fix conflicts first though before approval :)

**Comment by evanhearne** [comment]
@SinenWew changes have been made. I will review this now.

**Comment by evanhearne** [comment]
@SinenWew changes look good. Would you like to merge this yourself or would you like me to do it for you. If you're reading by email you can reply via email. :)

**Comment by evanhearne** [comment]
@SinenWew we discussed that I will merge this for you as you don't have write access.

**Pull request merged**
