### PR TITLE
✨ Feature: Introducing Suggested Photo Slider for review

### PR DESCRIPTION
**Pull request by judyobrienie**
# Description

Introducing a suggested photo slideshow, Images will still need to resized as per agreed size of slideshow.  Which still needs to be discussed by team.

Node: This was a code dump, just to get initial approval on style of slideshow.

## What

Slideshow

## Why

As per trello card

## How

As per code changes

## Verification Steps

This code is a temp suggested slideshow for the team to review and tidy code

# Checklist:

- [x] This pr is linked to the related trello card
- [ ] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@judyobrienie  this looks really slick already. Let's show the guys and definitely chat about this tomorrow.

**Comment by ciaranRoche** [comment]
@judyobrienie are you looking for an feedback on this, or is just an example to show tomorrow?

**Comment by judyobrienie** [comment]
@ciaranRoche @laurafitzgerald was just an initial idea to see if this is what the team are looking for. Research so to speak and a head start for us tomorrow morning.  If team are happy to go with same then the code can be cleaned up by me or anybody with the boys tomorrow morning.  Images will need to be resized also as they are all different on the drive.

**Comment by dimitraz** [comment]
@ciaranRoche still a WIP

**Comment by ciaranRoche** [comment]
@dimitraz cool thanks, just wanted to check before reviewing it is all.

**Comment by judyobrienie** [comment]
@dominikkawka @AdamLalor @maciejmarchel12 @KieranHanrahan @laurafitzgerald @JameelB @ciaranRoche @dimitraz 

Updated the slider, can you take a look?

**Pull request merged**
