### PR TITLE
added extra curricular activities

### PR DESCRIPTION
**Pull request by denispop9**
# Description

added extra curricular activities

## What

you are now able to see the extra curricular activities on the website

## Why

so that the extra curricular activities are seen on the website

## Verification Steps

What steps should be taken to verify that the change is working correctly

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by denispop9** [comment]
@evanhearne @laurafitzgerald could one of ye review this please :)

**Comment by evanhearne** [comment]
@denispop9 reviewing now.

**Comment by evanhearne** [comment]
@denispop9 thanks for adding changes. Reviewing now.

**Comment by evanhearne** [comment]
@denispop9 feel free to merge

**Pull request merged**
