### PR TITLE
added wse report

### PR DESCRIPTION
**Pull request by evanhearne**
# Description

WSE Report Added 

## What

WSE Report Added to `About` -->  `Inspection Reports`

## Why

Parents can access WSE Report on website

## Verification Steps

http-server, go to About --> Inspection Reports and ensure that WSE Report 2015 is there along with its contents.

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by evanhearne** [comment]
@laurafitzgerald can you please review this when you have the time? :)

**Comment by laurafitzgerald** [comment]
👀

**Comment by evanhearne** [comment]
That could perhaps be an option. I will ask them.

**Comment by evanhearne** [comment]
@laurafitzgerald spoke with @edkennedy50 and he would like to leave the document as is, however, he has asked me to center the document, which I did. Feel free to review when you have the time. :)

**Pull request merged**
