### PR TITLE
added image <3

### PR DESCRIPTION
**Pull request by bigpoloskipainter**
the image of the principal is now on the website

### CODE REVIEW

**Comment by evanhearne** [comment]
@bigpoloskipainter please redo your description, then I will review.

**Comment by evanhearne** [comment]
@bigpoloskipainter I will attach this PR to the trello card.

**Comment by bigpoloskipainter** [comment]
> the image of the principal is now on the website

ive completed the task

**Comment by evanhearne** [comment]
@bigpoloskipainter thanks, reviewing now.

**Comment by bigpoloskipainter** [comment]
@evanhearne merge this for me

**Comment by evanhearne** [comment]
@bigpoloskipainter no problem as you dont have access yet. will get access for you soon

**Comment by evanhearne** [comment]
@laurafitzgerald this was to add image into index.html just saying for records.

**Pull request merged**
