### PR TITLE
Added GitHub Authorisation Tutorial to docs folder

### PR DESCRIPTION
**Pull request by evanhearne**
I am adding this tutorial as I think it will benefit the newcomers to this project in the future.

# Description

New tutorial on how to authorize your computer for work on github has been added to the /docs folder. It has been added so that people will know how to authorize their computers for work on this project.

## What

A tutorial that wasn't previously available has been added for learning and teaching use.

## Why

This tutorial has been added because it will benefit future project workers, in my opinion. They will have easy access to a step-by-step process that will inevitably remove some stress from the setting up and continuation of the project.

## How

The ODF file was uploaded via GitHub and was added to a branch.

## Verification Steps

-Download file
-Open it using OpenOffice, LibreOffice, or Microsoft Office.
-Ensure all slides are present
-Leave a review or request below

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by evanhearne** [comment]
@denispop9 @laurafitzgerald please review when you have the time.

**Comment by evanhearne** [comment]
@laurafitzgerald conversion is completed. Please review when you have the time.

**Comment by evanhearne** [comment]
OK. I will have a look at that now @laurafitzgerald.

**Comment by evanhearne** [comment]
@laurafitzgerald could you explain to me what you meant by 'numbering' ? I'm not sure I understand.

**Comment by evanhearne** [comment]
@laurafitzgerald whatever issues I found with the document, I believe they're solved now. Step 3 won't become a title for me for some reason.

**Comment by evanhearne** [comment]
@laurafitzgerald changes requested have been completed, please review when you have the time.

**Comment by evanhearne** [comment]
@laurafitzgerald because @edkennedy50 wants as many changes made as possible to this master before you have a video conference on Wednesday, I will adjust the title to suit this for Fedora.

**Comment by laurafitzgerald** [comment]
@evanhearne that's no problem, could you create a card on the backlog to do the additional work to cover Windows. You can label it `setup` and link to this pr to show the source of the work

**Comment by evanhearne** [comment]
@laurafitzgerald done. Can you please review AUP Policy PR for me and @SinenWew? Thanks.

**Pull request merged**
