### PR TITLE
Fix logo typo

### PR DESCRIPTION
**Pull request by dominikkawka**
# Description

Changed logo to this
school logo

## What

Logo is changed
## Why

There was a typo in logo
## How

Remade the logo in ps 
## Verification Steps

open the website and see if worked. I made a second pr because I used wrong image, that's why you check before you make a pr.

# Checklist:

- [ ] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This change has been verified by another team member

### CODE REVIEW

**Comment by edkennedy50** [comment]
Just after viewing the change that you made to the logo. The spelling is
now correct.

**Comment by laurafitzgerald** [comment]
@dominikkawka this change looks good. I was able to build it locally and the spelling is now updated. Regarding the checklist in the description, do you have a trello card created for this change? What was the source of the change? If someone asked you to do it, I would encourage you to encourage them to create a trello card for it. :)

**Comment by edkennedy50** [comment]
That’s fine Evan.

**Comment by laurafitzgerald** [comment]
@evanhearne yes that's fine, you have access now to merge changes. It will be up to you guys to do the merging from now on. Use your best judgement around things that can and can't be merged. As long as the items in the checklist in the description are done and an Approval Review is added yee should be good.

**Pull request merged**
