### PR TITLE
Booklist Revision 2019/2020

### PR DESCRIPTION
**Pull request by evanhearne**
# Description

Booklists have been revised for the 2019/2020 school year

## What

Booklists from 1st-6th year have been modified for the 2019/2020 school year. Changes can be found in /pages/booklists/

## Why

A new academic year will begin, books required for the year WILL need to be displayed.

## Verification Steps

http-server, head to Booklists Tab in navbar and ensure that all booklist pages are working, without any errors or mistakes.

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This change has been verified by another team member

### CODE REVIEW

**Comment by evanhearne** [comment]
@laurafitzgerald @bigpoloskipainter hey I know it is a bit early, this card, but @edkennedy50 has asked me to work on this over the summer to submit. If a review is indeed possible please feel free to do so. :)

**Comment by laurafitzgerald** [comment]
👀

**Review by laurafitzgerald — APPROVED** [review]
Hi @evanhearne the change renders correctly locally. The code changes themselves look fine. I haven't checked the exact content against an original as I assume that you have made those changes correctly. Feel free to merge it. :)

**Comment by laurafitzgerald** [comment]
@evanhearne if this is going to be published soon, don't forget to tag the repo here to mark it as published.

**Comment by evanhearne** [comment]
Sure @laurafitzgerald. Also, I sent you an email regarding LCVP Work
Experience. I would appreciate it if you'd have a look at it.

**Pull request merged**
