### PR TITLE
Newsletter

### PR DESCRIPTION
**Pull request by evanhearne**
# Description

Newsletter Feature added to the website.

## What

January 2019 Newsletter is available.

## Why

Parents can now see Newsletters online

## Verification Steps

http-server it, see if `Newsletter` is present on the navbar. Page should show up with dropdown to Jan 2019 newsletter

# Checklist:

- [x] This pr is linked to the related trello card
- [x] My code follows the style guidelines of this project
- [x] I have requested a code review from (at least) two team members
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This change has been verified by another team member

### CODE REVIEW

**Comment by evanhearne** [comment]
@laurafitzgerald can you please review this when you have the time? :)

**Comment by evanhearne** [comment]
@laurafitzgerald I squashed the commits, but for some reason it says I dismissed your stale review. I found this link that supposedly tells you to fix this. https://github.com/isaacs/github/issues/1157#issuecomment-450409941 Meanwhile could you reapprove this branch so I can merge?

**Comment by laurafitzgerald** [comment]
@evanhearne I put a new setting over the weekend to dismiss an approval review on a force push. It's just another security approach in order to get changes verified again once a force push happens, just in case there is some problem with the force push.

**Comment by evanhearne** [comment]
@laurafitzgerald thanks for that. Merging now. :)

**Pull request merged**
